{
  "pictures": [
    {"src": "img/collage_photos/1.jpg", "title": "2004 - Estudiando"},
    {"src": "img/collage_photos/2.jpg", "title": "2005 - Casa de Naty"},
    {"src": "img/collage_photos/3.jpg", "title": "2005 - Colación Maxi"},
    {"src": "img/collage_photos/4.jpg", "title": "2005_Comiendo en Betos"},
    {"src": "img/collage_photos/5.jpg", "title": "2005_Con Cesar"},
    {"src": "img/collage_photos/6.jpg", "title": "2005_Criadero proyecto tesis de David"},
    {"src": "img/collage_photos/7.jpg", "title": "2005_Festejos graduación de Maxi"},
    {"src": "img/collage_photos/8.jpg", "title": "2005_Fiesta fin cursado en la facultad"},
    {"src": "img/collage_photos/9.jpg", "title": "2005_Graduación Maxi"},
    {"src": "img/collage_photos/10.jpg", "title": "2005_Haciendo el asado en el patio casa David"},
    {"src": "img/collage_photos/11.jpg", "title": "2005_Patio casa de Naty"},
    {"src": "img/collage_photos/12.jpg", "title": "2005_Trabajando en Vates"},
    {"src": "img/collage_photos/13.jpg", "title": "2006_Almorzando antes de volver al trabajo"},
    {"src": "img/collage_photos/14.jpg", "title": "2006_Casa_Naty"},
    {"src": "img/collage_photos/15.jpg", "title": "2006_Cena 80 años Abuelo Raul"},
    {"src": "img/collage_photos/16.jpg", "title": "2006_En el cine"},
    {"src": "img/collage_photos/17.jpg", "title": "2006_En el lago los molinos"},
    {"src": "img/collage_photos/18.jpg", "title": "2006_En el Zoo"},
    {"src": "img/collage_photos/19.jpg", "title": "2006_En la clinica Caraffa esperando mama naty"},
    {"src": "img/collage_photos/20.jpg", "title": "2006_En Motorola con Rodrigo Ochoa"},
    {"src": "img/collage_photos/21.jpg", "title": "2006_Fiesta 80 años abuelo Raul"},
    {"src": "img/collage_photos/22.jpg", "title": "2006_Pescando"},
    {"src": "img/collage_photos/23.jpg", "title": "2006_Preparativos para festejar el cumple de Naty"},
    {"src": "img/collage_photos/24.jpg", "title": "2006_Visita al Zoo"},
    {"src": "img/collage_photos/25.jpg", "title": "2007_Almuerzo casa Naty"},
    {"src": "img/collage_photos/26.jpg", "title": "2007_Aqualokos Brasil"},
    {"src": "img/collage_photos/27.jpg", "title": "2007_Camino a Torres Brasil"},
    {"src": "img/collage_photos/28.jpg", "title": "2007_Comiendo Paella en El Celta"},
    {"src": "img/collage_photos/29.jpg", "title": "2007_Con el Morro de Torres Brasil"},
    {"src": "img/collage_photos/30.jpg", "title": "2007_Con Fer en el cumple de Baty"},
    {"src": "img/collage_photos/31.jpg", "title": "2007_Con Luciana"},
    {"src": "img/collage_photos/32.jpg", "title": "2007_Despues de presentar Tesis David"},
    {"src": "img/collage_photos/33.jpg", "title": "2007_El Peugeot"},
    {"src": "img/collage_photos/34.jpg", "title": "2007_El sol nos quemo en Brasil"},
    {"src": "img/collage_photos/35.jpg", "title": "2007_En el bus hacia Brasil"},
    {"src": "img/collage_photos/36.jpg", "title": "2007_En el cumpleaños de Rodrigo en Totoral"},
    {"src": "img/collage_photos/37.jpg", "title": "2007_En el tren de Torres"},
    {"src": "img/collage_photos/38.jpg", "title": "2007_En la calles de Torres Brasil"},
    {"src": "img/collage_photos/39.jpg", "title": "2007_En la casa de la Naty"},
    {"src": "img/collage_photos/40.jpg", "title": "2007_En la pileta del hotel en Brasil"},
    {"src": "img/collage_photos/41.jpg", "title": "2007_Esperando Tesis David"},
    {"src": "img/collage_photos/42.jpg", "title": "2008_Anfiteator_Mina Clavero"},
    {"src": "img/collage_photos/43.jpg", "title": "2008_Casa_David"},
    {"src": "img/collage_photos/44.jpg", "title": "2008_Cena en el cumpleaños de papa David"},
    {"src": "img/collage_photos/45.jpg", "title": "2008_Con la Mona Lisa"},
    {"src": "img/collage_photos/46.jpg", "title": "2008_David en Barcelona"},
    {"src": "img/collage_photos/47.jpg", "title": "2008_David en el Coliseo"},
    {"src": "img/collage_photos/48.jpg", "title": "2008_David en el museo de Louvre"},
    {"src": "img/collage_photos/49.jpg", "title": "2008_David en Paris"},
    {"src": "img/collage_photos/50.jpg", "title": "2008_Descansando en la cabañas de Victor en Mina Clavero"},
    {"src": "img/collage_photos/51.jpg", "title": "2008_En flia - Cumple_Naty"},
    {"src": "img/collage_photos/52.jpg", "title": "2008_En la cabañas de Victor en Mina Clavero"},
    {"src": "img/collage_photos/53.jpg", "title": "2008_Festejo cumple papi"},
    {"src": "img/collage_photos/54.jpg", "title": "2008_Mina Clavero"},
    {"src": "img/collage_photos/55.jpg", "title": "2008_Naty En La Serranita"},
    {"src": "img/collage_photos/56.jpg", "title": "2008_Nuestros_Papis en el TC"},
    {"src": "img/collage_photos/57.jpg", "title": "2009_Cascada del Toro Muerto - David"},
    {"src": "img/collage_photos/58.jpg", "title": "2009_Cascada del Toro Muerto - Naty"},
    {"src": "img/collage_photos/59.jpg", "title": "2009_Cenando en Casa Naty"},
    {"src": "img/collage_photos/60.jpg", "title": "2009_Chilecito_Primos,Tia,Hermanas Naty"},
    {"src": "img/collage_photos/61.jpg", "title": "2009_Descansando_En Cura Brochero"},
    {"src": "img/collage_photos/62.jpg", "title": "2009_En nono con la Flia"},
    {"src": "img/collage_photos/63.jpg", "title": "2009_Graduacion David"},
    {"src": "img/collage_photos/64.jpg", "title": "2009_Graduacion Facultad David"},
    {"src": "img/collage_photos/65.jpg", "title": "2009_Mina Clavero - David"},
    {"src": "img/collage_photos/66.jpg", "title": "2009_Mina Clavero - Naty"},
    {"src": "img/collage_photos/67.jpg", "title": "2009_Mina Clavero Cabaña Carlitos"},
    {"src": "img/collage_photos/68.jpg", "title": "2010_Abuela Lola Y Tia Teresa"},
    {"src": "img/collage_photos/69.jpg", "title": "2010_Casa de alfajores - La Cumbresita"},
    {"src": "img/collage_photos/70.jpg", "title": "2010_Con la Estatua de la Libertad"},
    {"src": "img/collage_photos/71.jpg", "title": "2010_David en Chicago"},
    {"src": "img/collage_photos/72.jpg", "title": "2010_David en el Time Square"},
    {"src": "img/collage_photos/73.jpg", "title": "2010_En el punte de la Cumbresita"},
    {"src": "img/collage_photos/74.jpg", "title": "2010_En el terreno - Siete Soles"},
    {"src": "img/collage_photos/75.jpg", "title": "2010_En la Cumbresita"},
    {"src": "img/collage_photos/76.jpg", "title": "2010_En_el_Condor"},
    {"src": "img/collage_photos/77.jpg", "title": "2010_La Cumbresita"},
    {"src": "img/collage_photos/78.jpg", "title": "2010_Naty en el trabajo - Kolektor"},
    {"src": "img/collage_photos/79.jpg", "title": "2010_Paseando_En la Cumbresita"},
    {"src": "img/collage_photos/80.jpg", "title": "2010_El Fiat Punto"},
    {"src": "img/collage_photos/81.jpg", "title": "2010_Relajado_en_Mina_Clavero"},
    {"src": "img/collage_photos/82.jpg", "title": "2010_Salida_con_amigos"},
    {"src": "img/collage_photos/83.jpg", "title": "2010_Visitando_La Cumbresita"},
    {"src": "img/collage_photos/84.jpg", "title": "2011_Egreso_Naty con David"},
    {"src": "img/collage_photos/85.jpg", "title": "2011_Egreso_Naty con Flia"},
    {"src": "img/collage_photos/86.jpg", "title": "2011_en_el_Obelisco"},
    {"src": "img/collage_photos/87.jpg", "title": "2011_En_Obserbatorio_BsAs"},
    {"src": "img/collage_photos/88.jpg", "title": "2011_Nuestras_Mascotas"},
    {"src": "img/collage_photos/89.jpg", "title": "2011_Nuestro_Primer_Arbolito"},
    {"src": "img/collage_photos/90.jpg", "title": "2011_Por_BsAS_La_Boca"},
    {"src": "img/collage_photos/91.jpg", "title": "2011_Previa_Partido_Argentina"},
    {"src": "img/collage_photos/92.jpg", "title": "2012_Carlos_Paz"},
    {"src": "img/collage_photos/93.jpg", "title": "2012_Las_tres_Reynas en Carlos Paz"},
    {"src": "img/collage_photos/94.jpg", "title": "2012_Nochebuena"},
    {"src": "img/collage_photos/95.jpg", "title": "2013_Año nuevo - En casa_Naty"},
    {"src": "img/collage_photos/96.jpg", "title": "2013_El tropezon desde el Balcon"},
    {"src": "img/collage_photos/97.jpg", "title": "2013_Festejo compromiso en Cartagena"},
    {"src": "img/collage_photos/98.jpg", "title": "2013_Isla palma con palmeras"},
    {"src": "img/collage_photos/99.jpg", "title": "2013_Isla Palma"},
    {"src": "img/collage_photos/100.jpg", "title": "2013_Naty en el depto"},
    {"src": "img/collage_photos/101.jpg", "title": "Isla Palma con Amigos"}

  ]
}